[package]
name = "libiouring"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
libc = { version = "0.2" }
static_assertions = "1.1.0"

[build-dependencies]
bindgen = { version = "0.64" }
